roomFinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #...
    path('', include("roomFinder_app.urls")),
    path('accounts/', include('allauth.urls')),
    path('logout', LogoutView.as_view()),
    path('admin/', admin.site.urls)
]

roomFinder_app/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView


app_name = "roomFinder_app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("map/", TemplateView.as_view(template_name="map.html"), name="map"),
    path('room_list/<str:building_value>/', views.room_list, name='room_list'),
    path("room_list/<int:pk>/details/", views.RoomDetailView.as_view(), name="room_detail"),
    path("reservations/<int:pk>/details/", views.ReservationDetailView.as_view(), name="reservation_detail"),
    path("reservations/", views.ReservationListView.as_view(), name="reservation_list"),
    path("messages/<int:pk>/details/", views.MessageDetailView.as_view(), name="message_detail"),
    path("message/<int:pk>/details/delete", views.delete_message, name="delete_message"),
    path("messages/", views.MessageListView.as_view(), name="message_list"),
    path("create/", views.CreateResView.as_view(), name="create_reservation"),
    path("create/make_res", views.make_reservation, name="make_res"),
    path("add_new_room/", views.AddRoomView.as_view(), name="add_new_room"),
    path("add_new_room/add_room", views.add_room, name="add_room"),
    path("approve_rooms/", views.UnapprovedRoomsList.as_view(), name="unapproved_rooms"),
    path("room_list/<int:pk>/details/approve", views.approve_room, name="approve_room"),
    path("room_list/<int:pk>/details/delete", views.delete_room, name="delete_room"),
    path('reservation/<int:pk>/delete/', views.admin_delete_reservation, name='delete_reservation'),
]

roomFinder_app/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.models import Permission
#from django.contrib.postgres.fields import ArrayField


# Create your models here.

class Room(models.Model):
    room_name = models.CharField(max_length=100)
    building = models.CharField(max_length=100)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return str(self.room_name) + " " + self.building

class Reservation(models.Model):
    title = models.CharField(max_length=100)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    day = models.CharField(max_length=15)
    created_at = models.DateTimeField(auto_now_add=True)

    def was_created_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.created_at <= now

    def __str__(self):
        return self.title + ": " + str(self.user) + " - " + str(self.room)

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    message = models.CharField(max_length=200)

    def __str__(self):
        return str(self.title)

class RoomRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

roomFinder_app/forms.py
from django.forms import ModelForm, inlineformset_factory
from django.contrib.auth.models import User
from .models import Reservation, Room


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = ['room_name','building']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', ]


class ReservationForm(ModelForm):
    class Meta:
        model = Reservation
        fields = ['title', 'room', 'user', 'start_time', 'end_time', 'day']


"""
TO-DO: form to add a reservation, reservation must connect to a room and user
ReservationFormSet = inlineformset_factory(Room, User, Reservation form=ReservationForm, extra=0, can_delete=False, min_num=1, validate_min=True,)
"""

roomFinder_app/views.py
# *  REFERENCES
# *  ----------
# *  Title: Hotel-Room-Booking-System
# *  Author: SurajGuptaRavi
# *  Date: 2020
# *  URL: https://github.com/SurajGuptaRavi/Hotel-Room-Booking-System/blob/master/Krishna_Hotel/hotel/krishna/views.py
# *  used book_room function (lines 244-283) as a starting point for
# *  for our make_reservation function (lines 160-207)


from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.db import IntegrityError
from django.views import generic
from django.contrib.auth.models import User
from django.contrib import messages
from .models import Room, Reservation, Message, RoomRequest
from .forms import ReservationForm, RoomForm
from django.views.generic import CreateView
from django.core.exceptions import ObjectDoesNotExist
# from separate import room_generate
import datetime
import json
import pandas as pd
import requests
from datetime import timedelta,datetime
import re

def dummy_user():
    try:
        return User.objects.get(username='class time')
    except ObjectDoesNotExist:
        print("Create a Dummy User")

def import_data():
    try:
        user = dummy_user()
        df = pd.read_csv("roomFinder_app/class_res.csv")
        for index, row in df.iterrows():
            if not Room.objects.filter(room_name=row['Room'], building=row['Building']).exists():
                room = Room(room_name=row['Room'],building=row['Building'])
                room.save()
            room = Room.objects.get(room_name=row['Room'],building=row['Building'])
            reservation = Reservation(title='Class',room=room,user=user,start_time=datetime.strptime(str(row['Start_time']), '%H.%M'),
                                      end_time=datetime.strptime(row['End_time'], '%H:%M:%S'),day=row['Days'])
            reservation.save()
    except IntegrityError:
        print("Create a Dummy User")

building_coordinates = {'Astronomy Bldg': "38.035568, -78.515187", 'Biomed Engr & Med Sci': "38.030433, -78.499735", 'Bond House': "38.0293, -78.5041", 
                        'Brooks Hall': "38.035750, -78.502092", 'Brown Hall': "38.052923, -78.509306", 'Bryan Hall': "38.033263, -78.505940",
                        'Campbell Hall': "38.038724, -78.503845", 'Chemical Engineering Bldg': "38.033410, -78.510739", 'Chemistry Bldg': "38.033539, -78.511657",
                        'Clark Hall': "38.032998, -78.507857", 'Claude Moore Nursing Educ': "38.030769, -78.501686", 'Clemons Library': "38.036417, -78.506061",
                        'Cocke Hall': "38.033400, -78.505220", 'Collins Wing': "38.033348, -78.501611", 'Darden Classroom Bldg Room': "38.052551,-78.514637",
                        "Dawson's Row": "38.032250,-78.506411", 'Dell': "38.034913,-78.509954", 'Drama Education Bldg': "38.039623,-78.504383",
                        'Fayerweather Hall': "38.037815,-78.503079", 'French House': "38.031654,-78.502109", 'Gibson Hall': "38.031342,-78.505156",
                        'Gilmer Hall': "38.034132,-78.512746", 'Hunter Smith Band Building': "38.039856,-78.502925", 'Jesser Hall': "38.033120,-78.510882",
                        'John W. Warner Hall': "38.033378,-78.506791", 'Kerchof Hall': "38.032286,-78.508183", 'Lacy Room': "38.035640,-78.517774",
                        'Legal Aid Justice Center': "38.039149,-78.491610", 'Lower West Oval Room': "38.035704,-78.503531", 'Martha Jefferson Hospital CRN': "38.022735,-78.444283",
                        'McLeod Hall': "38.030881,-78.501646", 'Mechanical Engr Bldg': "38.032601,-78.511036", 'Memorial Gymnasium': "38.037373,-78.507181",
                        'Minor Hall': "38.033828,-78.506503", 'Monroe Hall': "38.034892,-78.506160", 'Multistory (Old) Hospital': "38.033270,-78.501137",
                        'Nau Hall': "38.031695,-78.504926", 'New Cabell Hall': "38.032540,-78.505108", 'Observ Mtn Eng Res Fac G': "38.041211,-78.521048",
                        'Old Cabell Hall': "38.032835,-78.504867", 'Olsson Hall': "38.031966,-78.510484", 'Pavilion V': "38.034970,-78.504193",
                        'Pavilion VIII': "38.034372,-78.503607", 'Physical & Life Sci Bldg Rm': "38.032850,-78.512241", 'Physics Bldg': "38.034252,-78.510244",
                        'PINN Hall': "38.031832,-78.500508", 'Randall Hall': "38.033251,-78.503314", 'Rice Hall': "38.031581,-78.510751",
                        'Ridley Hall': "38.034917,-78.509096", 'Robertson Hall': "38.032988,-78.503943", 'Rouss Hall': "38.032988,-78.503943",
                        'Ruffin Hall': "38.039320,-78.503173", 'Sands Captl Mgmt Bldg Rm': "38.052720,-78.514398", 'Shannon House': "38.033578,-78.514953",
                        'Slaughter Hall': "38.053259,-78.510573", 'Slaughter Rec': "38.034804,-78.517928", 'Student Health & Wellness': "38.030207,-78.503798",
                        'The Rotunda Room': "38.035594,-78.503352", 'Thornton Hall A': "38.033243,-78.509708", 'Thornton Hall D': "38.032905,-78.510245",
                        'Thornton Hall E': "38.032364,-78.510438", 'University Health Sciences': "38.031594,-78.500793", 'Wilsdorf Hall': "38.033303,-78.511243",
                        'Wilson Hall': "38.032455,-78.504022"} 

def room_list(request, building_value):
    objects = Room.objects.all().filter(building=building_value, approved=True)
    return render(request, 'room_list.html', {'objects': objects, 'building_value': building_value, 'building_coord': building_coordinates})

class IndexView(generic.ListView):
    template_name = "index.html"
    context_object_name = "building_list"
    if Reservation.objects.count() < 6756:
        import_data()

    def get_queryset(self):
        seen = set()
        uniqueBuildings = []
        for room in Room.objects.all().order_by('building'):
            if room.building not in seen and room.approved == True:
                seen.add(room.building)
                uniqueBuildings.append(room.building)
        return uniqueBuildings


class UnapprovedRoomsList(generic.ListView):
    template_name = "unapproved_rooms.html"
    context_object_name = "unapproved_rooms_list"

    def get_queryset(self):
        return Room.objects.filter(approved=False)

def approve_room(request, pk):
    room = get_object_or_404(Room, pk=pk)
    room.approved = True;
    room.save()
    return redirect("roomFinder_app:unapproved_rooms")

def delete_room(request, pk):
    room = get_object_or_404(Room, pk=pk)
    room_req = RoomRequest.objects.filter(room=room).get()
    to_user = room_req.user
    message = Message()
    message.user = to_user
    message.message = str(room) + " does not exist at UVA. We deleted your request."
    message.title = "Regarding " + str(room)
    message.save()
    room.delete()
    return redirect("roomFinder_app:unapproved_rooms")

def delete_message(request, pk):
    message = get_object_or_404(Message, pk=pk)
    message.delete()
    return redirect("roomFinder_app:message_list")

class MessageListView(generic.ListView):
    template_name = "message_list.html"
    context_object_name = "message_list"

    def get_queryset(self):
        user = self.request.user
        return Message.objects.filter(user=user).order_by('-pk')

class MessageDetailView(generic.DetailView):
    model = Message
    template_name = "message_detail.html"

    def get_queryset(self):
        return Message.objects.all()

class RoomDetailView(generic.DetailView):
    model = Room
    template_name = "room_detail.html"
    
    def get_queryset(self):
        return Room.objects.all()


class RoomListView(generic.ListView):
    template_name = "room_list.html"
    context_object_name = "room_list"

    def get_queryset(self):
        return Room.objects.all()

def add_room(request):
    if request.method == "POST":
        building = request.POST['building']
        room_name = request.POST['room_name']
        if building == "" or room_name == ""  or building.isspace() or room_name.isspace():
            messages.warning(request, "Please enter all information")
            return HttpResponseRedirect(reverse('roomFinder_app:add_new_room'))
        if Room.objects.filter(room_name=room_name, building=building).exists():
            messages.warning(request, "This room already exists")
            return HttpResponseRedirect(reverse('roomFinder_app:add_new_room'))
        room = Room()
        room.room_name = room_name
        room.building = building
        room.save()
        room_req = RoomRequest()
        current_user = request.user
        user_object = User.objects.all().get(username=current_user)
        room_req.user = user_object
        room_req.room = room
        room_req.save()
        messages.info(request, "Room submitted")

        return HttpResponseRedirect(reverse('roomFinder_app:add_new_room'))
    else:
        return HttpResponse('Access Denied')



def make_reservation(request):
    if request.method == "POST":
        try:
            if request.POST['title'] == "" or request.POST['title'].isspace():
                messages.warning(request, "Please enter a title.")
                return HttpResponseRedirect(reverse('roomFinder_app:create_reservation'))
            building = request.POST['building']
            room_name = request.POST['room_name']
            room = Room.objects.all().get(room_name=room_name, building=building)
            input_start_time = datetime.time(datetime.strptime(request.POST['start_time'], '%H:%M'))
            input_end_time = datetime.time(datetime.strptime(request.POST['end_time'], '%H:%M'))
            for reservation in Reservation.objects.all().filter(room=room):
                if not(reservation.day == request.POST['day']):
                    pass
                else:
                    if reservation.start_time > input_start_time and reservation.start_time >= input_end_time > input_start_time:
                        pass

roomFinder_app/templates/add_new_room.html
{% include 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <div class="content">
        <h1>Add a Room</h1>
        <hr>
        <form action="{% url 'roomFinder_app:add_room' %}" method="post">
            {% csrf_token %}
            {% for msg in messages %}
                {% if msg.tags == 'warning' %}
                    <div class="alert alert-warning alert-dismissile" role="alert">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ msg }}</div>
                {% endif %}
                {% if msg.tags == 'info' %}
                    <div class="alert alert-success alert-dismissile" role="alert">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ msg }}</div>
                {% endif %}
            {% endfor %}
            <fieldset style="margin-top:50px">
                <div class="form-group">
                    <label for="room_name" class="form-label">Room Number: </label>
                    <input type="text" id="room_name" name="room_name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="building" class="form-label">Building: </label>
                    <input type="text" id="building" name="building" class="form-control">
                </div>
            </fieldset>
            <input type="submit" class="btn btn-outline-primary mt-3" value="Submit">
        </form>
    </div>
</body>
</html>

roomFinder_app/templates/index.html
<!--

REFERENCES

Title: Geolocation: Displaying User or Device Position on Maps
Date: 2023-11-16
URL: https://developers.google.com/maps/documentation/javascript/geolocation
Software License: code samples are licensed under the Apache 2.0 License.
Usage: Used tutorial to implement a map to show current location of user

-->

{% extends 'sidebar.html' %}
{% load socialaccount %}
{% load static %}
{% load auth_extras %}
<!doctype html>
<html lang="en" style="height: 100%;">
  <head>
    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3KKFuePsefgmgXPsYzqD2SFydD_rlUIM&callback=initMap&libraries=maps,marker&v=beta">
    </script>

    <script>
      function initMap() {
        console.log('Maps JavaScript API loaded.');
      }
    </script>
  </head>
  <body>
    <!-- Admin Page -->
    {% if request.user|has_group:"admin" %}
      {% block admin-content %}
      <!-- Admin Content -->
      <div class="content">
        <h1>Home</h1>
          <hr>
        <p>You are an admin! You are logged in as {{ user.username }}. Your email is {{ user.email }}.</p>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

        <link rel="stylesheet" type="text/css" href="/static/roomFinder_app/style.css" />
        <script type="module" src="/static/roomFinder_app/index.js"></script>

        <div id="map" style="width: 700px; height: 700px;" ></div>
        <script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
    ({key: "AIzaSyD3KKFuePsefgmgXPsYzqD2SFydD_rlUIM", v: "weekly"});</script>
        <a href="{% url 'roomFinder_app:reservation_list'%}">View Reservations</a>
      </div>
      {% endblock admin-content %}
    <!-- User Page -->
    {% elif user.is_authenticated %}
    <!-- User Content -->
    {% block user-content %}
      <div class="content">
        <h1>Home</h1>
          <hr>
        <div class="row">
          <div class="col">
            <h2>Buildings</h2>
            <div class="card" style="height:700px;">
              <div class="overflow-auto">
            {% if building_list %}
                <ul>
                   {% for building_value in building_list %}
                        <li><a href="{% url 'roomFinder_app:room_list' building_value %}">{{ building_value }}</a></li>
                   {% endfor %}
                </ul>
            {% else %}
                <p>No rooms available</p>
            {% endif %}
              </div>
            </div>
            <a href="{% url 'roomFinder_app:add_new_room' %}" class="btn btn-outline-primary mt-2 mb-2">Don't see a room you want? Click here to request to add a new room</a>

          </div>
          <div class="col">
            <h2>Map</h2>
            <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

            <link rel="stylesheet" type="text/css" href="/static/roomFinder_app/style.css" />
            <script type="module" src="/static/roomFinder_app/index.js"></script>

            <div id="map" style="width: 700px; height: 700px;" ></div>
            <script>(g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
        ({key: "AIzaSyD3KKFuePsefgmgXPsYzqD2SFydD_rlUIM", v: "weekly"});</script>
          </div>
        </div>
      </div>
    {% endblock user-content %}
    {% endif %}

    <!-- Optional Bootstrap JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

roomFinder_app/templates/message_detail.html
{% include 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div class="content">
    <h1>Title: {{ message.title }}</h1>
    <hr>
      <p>{{ message.message }} </p>
      <a href="{% url 'roomFinder_app:delete_message' message.id %}" class="btn btn-outline-primary">Delete Message</a>
  </div>
</body>
</html>

roomFinder_app/templates/message_list.html
{% include 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="content">
    <h1>Your Messages</h1>
    <hr>
    {% if message_list %}
        <ul>
           {% for message in message_list %}
                <li><a href="{% url 'roomFinder_app:message_detail' message.id %}">{{ message }}</a></li>
           {% endfor %}
        </ul>
    {% else %}
        <p>No messages</p>
    {% endif %}
</div>
</body>
</html>

roomFinder_app/templates/reservation_detail.html
{% load auth_extras %}
{% include 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <div class="content">
        <h1>Title: {{ reservation.title }}</h1>
        <hr>
        <p>Room: {{ reservation.room }}</p>
        <p>Day: {{ reservation.day }}</p>
        <p>Start Time: {{ reservation.start_time }}</p>
        <p>End Time: {{ reservation.end_time }}</p>
        {% if request.user|has_group:"admin" %}
            <p>User: {{ reservation.user }}</p>
        {% endif %}
        <a href="{% url 'roomFinder_app:delete_reservation' reservation.id %}" class="btn btn-outline-primary">Delete</a>
        <a href="{% url 'roomFinder_app:reservation_list'%}" class="btn btn-outline-primary">Back to Reservations</a>
    </div>
</form>
</body>
</html>

roomFinder_app/templates/room_detail.html
{% load auth_extras %}
{% include 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <div class="content">
        <h1>Room: {{ room.room_name }}</h1>
        <hr>
        <p>Location: {{ room.building }}</p>
        {% if request.user|has_group:"admin" %}
            <a href="{% url 'roomFinder_app:approve_room' room.id %}" class="btn btn-outline-primary">Approve</a>
            <a href="{% url 'roomFinder_app:delete_room' room.id %}" class="btn btn-outline-primary">Delete</a>
            <a href="{% url 'roomFinder_app:unapproved_rooms'%}" class="btn btn-outline-primary">Back</a>
        {% endif %}
    </div>
</body>
</html>

roomFinder_app/templates/sidebar.html
{% load socialaccount %}
{% load static %}
{% load auth_extras %}
<!doctype html>
<html lang="en" style="height: 100%;">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>RoomFinder</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'roomFinder_app/style.css' %}" />

    <script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD3KKFuePsefgmgXPsYzqD2SFydD_rlUIM&callback=initMap&libraries=maps,marker&v=beta">
    </script>

    <script>
      function initMap() {
        console.log('Maps JavaScript API loaded.');
      }
    </script>
  </head>
  <body>
    <!-- Admin Page -->
    {% if request.user|has_group:"admin" %}
      <!-- Navigation Bar -->
      <div class="sidenav">
        <a class="title" href="{% url 'roomFinder_app:index'%}">RoomFinder</a>
        <!-- Admin Pages -->
        <h3><u>Admin</u></h3>
        <a href="{% url 'roomFinder_app:reservation_list'%}">All Reservations</a>
        <a href="{% url 'roomFinder_app:unapproved_rooms'%}">Approve Rooms</a>
        <!-- User Pages -->
        <h3><u>User</u></h3>
        <a href="{% url 'roomFinder_app:create_reservation'%}">Book a Room</a>
        <a href="{% url 'roomFinder_app:add_new_room'%}">Add a Room</a>

        <a class="btn btn-secondary" href="{% url 'account_logout' %}"  role="button">Sign out</a>
      </div>
      <!-- Admin Content -->
      {% block admin-content %}
      {% endblock admin-content %}
    <!-- User Page -->
    {% elif user.is_authenticated %}
      <!-- Navigation Bar -->
      <div class="sidenav">
        <a class="title" href="{% url 'roomFinder_app:index'%}">RoomFinder</a>
        <a href="{% url 'roomFinder_app:index'%}">Home</a>
        <a href="{% url 'roomFinder_app:create_reservation'%}">Book a Room</a>
        <a href="{% url 'roomFinder_app:reservation_list'%}">Current Reservations</a>
        <a href="{% url 'roomFinder_app:add_new_room'%}">Add a Room</a>
        <a href="{% url 'roomFinder_app:message_list'%}">Messages</a>
        <a class="btn btn-secondary" href="{% url 'account_logout' %}"  role="button">Sign out</a>
      </div>
      <!-- User Content -->
      {% block user-content %}
      {% endblock user-content %}
    {% else %}
      <div class="login-container">
        <h1>RoomFinder</h1>
        <a class="btn btn-primary" href="{% url 'account_login' %}">Sign In</a>
      </div>
    {% endif %}

    <!-- Optional Bootstrap JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

roomFinder_app/templates/unapproved_rooms.html
{% extends 'sidebar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block admin-content %}
<div class="content">
    <h1>Approve Rooms</h1>
    <hr>
    {% if unapproved_rooms_list %}
        <ul>
           {% for room in unapproved_rooms_list %}
                <li><a href="{% url 'roomFinder_app:room_detail' room.id %}">{{ room }}</a></li>
           {% endfor %}
        </ul>
    {% else %}
        <p>No rooms to approve</p>
    {% endif %}
</div>
{% endblock admin-content %}
</body>
</html>